sudo: false
language: node_js
node_js:
  - "8.9.3"
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm
before-script:
  - npm run test
  - npm run cover
  - npm run check-coverage